# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://localhost:4000"  # Development URL
# url: http://stefanimhoff.de # Live URL
title: "Stefan Imhoff"
description: "Frontend Engineer @ XING, Designer, Martial Artist and hobby philosopher."
keywords: "Stefan Imhoff, Hamburg, Frontend, Engineer"
author: "Stefan Imhoff"
subscribe_rss: "/atom.xml"
date_format: "%d.%m.%Y"
titlecase: false

# ----------------------- #
#    Jekyll/Plugins     #
# ----------------------- #

root: /
permalink: /:title/ # /blog/:title/, /notebook/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: thema
category_title_prefix: "Thema: "
tag_dir: tags
tag_title_prefix: "Tags: "
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb
lsi: true # Related posts

# Jekyll Assets
assets:
  dirname: assets
  # baseurl: //my.super-cool-cdn.com/
  sources:
    - css
    - js
    - img
  compress:
    js: closure # uglify, yui
    css: sass # yui

# Pagination
paginate: 150
recent_posts: 5
excerpt_link: "Weiterlesen &rarr;"
