# =============== #
# Jekyll Settings #
# =============== #

# URLs/Paths
baseurl:   ""
url:       "http://0.0.0.0:9999"
root:      /
permalink: /:year/:title/

# Jekyll
source:      ./app
destination: ./build/development

# Gems
gems:
  - jekyll-paginate

# Publishing
encoding:    "utf-8"
criticalcss: false
future:      true
show_drafts: true
limit_posts: 20
# limit_posts: 0

# Server
date_format: "%d.%m.%Y"
titlecase:   false
port:        8888
timezone:    local
markdown:    kramdown
lsi:         true
language:    "en"

# Feeds
excerpt_link: "Read more &arr;"
excerpt_in_feed: false
permalink_label: "Permalink"
permalink_label_feed: "★ Permalink"
linklog_marker: "→"
linklog_marker_position: after
linklog_marker_position_feed: after
standard_post_marker:

# Categories
category_feeds: true
category_dir: category
category_title_prefix: "Category: "
category_meta_description_prefix: "This site has an overview of all articles you can find on this website in the category: "

# Tags
tag_feeds: true
tag_dir: tag
tag_title_prefix: "Tags: "
tag_meta_description_prefix: "This site has an overview of all articles you can find on this website, which are tagged with: "

# Pagination
paginate:       1000       # Posts per page on the blog index
paginate_path:  :num       # default path for pagination, eg. page/2/

# Markdown
kramdown:
  auto_ids:                  false
  auto_id_prefix:            ""
  auto_id_stripping:         true
  transliterated_header_ids: true
  footnote_nr:               1
  entitiy_output:            as_char
  toc_levels:                1..6
  input:                     GFM # GitHub Flavored Markdown
  smart_quotes:              sbquo,lsquo,bdquo,ldquo, # ‚‘ „“
  # smart_quotes:              apos,apos,quot,quot # '' ""

# Exclude files, Gulp.js handles the assets
exclude: [
  "vendor", "Gemfile", "Gemfile.lock", "README.markdown", "fonts",
  "**.png", "**.jpg", "**.jpeg", "**.gif", "**.webp", "**.svg", "**.ico"
]

include: [".htaccess", ".htpasswd", "favicon.ico"]


# Attribution
# ===========

# Bambus
# ------
attribution_name: "「大宮盆栽×タムロン」大宮盆栽美術館で盆栽撮影にチャレンジ！ブロガーイベント"
attribution_url: "https://www.flickr.com/photos/norio-nakayama/9156103138"
attribution_author: "Norio NAKAYAMA"
attribution_creative_commons: true
attribution_language: "ja"

# Zitrone
# -------
# attribution_name: "solo sunshine"
# attribution_url: "https://www.flickr.com/photos/suttonhoo22/328647662/"
# attribution_author: "Dayna Bateman"
# attribution_creative_commons: true

# Zapfen
# ------
# attribution_name: "european larch"
# attribution_url: "https://www.flickr.com/photos/suttonhoo22/616628892/"
# attribution_author: "Dayna Bateman"
# attribution_creative_commons: true

# Halloween
# ---------
# attribution_name: "25/50"
# attribution_url: "https://www.flickr.com/photos/mmortah/5115158216"
# attribution_author: "Marian Hilditch"
# attribution_creative_commons: true
