# ==================== #
# Jekyll-Einstellungen #
# ==================== #

# Seiten-Einstellungen
title:       kogakure.de – Ninja, Ninjutsu und Kampfkunst
email:       mail@kogakure.de
description: "Fachmagazin für Ninja, Ninjutsu und Kampfkunst."
keywords:    "Ninjutsu, Ninja, Ninpo, Schattenkrieger, Shinobi, Kunoichi, Shadowwarrior, Tengu, Bujinkan, Budo, Taijutsu, BBD, Ryu, Ryuha, Sensei, Soke, Masaaki Hatsumi, Takamatsu, Toda, Hayes, Kampf, Kampfkunst, Krieger, Kriegskunst, Martial Arts, Selbstverteidigung, Sport, Geheimnis, Geschichte, Iga, Koga, Shidoshi, Shihan, Philosopie, Schwertkampf, Spionage, Sabotage, Guerilla, Verstecken, Waffen, Natur, Satori, Tradition, Japan, Asien, Inton, Erleuchtung, Goton-po, Budô, Bujin, Godai, Gogyo, Hojutsu, Junan Taiso, Jutsu, Jutte, Meditation, Meso, Mikkyo, Nahkampf, Shugendo, Tobi, Training, Ukemi, Waffen, Yamabushi, Sennin, Jônin, Chunin, Genin, Kamae, Kogakure, Bisento, Bo, Bokken, Kama, Ken, Kuji-in, Kuji-kiri, Kusarifundo, Kyoketsu Shoge, Metsubishi, Naginata, Kyoketsu Shoge, Shuko, Shuriken, Tanto, Tekagi, Tessen, Wurfstern, Yari, Zue"
author:      Stefan Imhoff

# URLs und Pfade
baseurl:   ""
url:       "http://0.0.0.0:8888"
root:      /
permalink: /artikel/:title/

# Jekyll Pfade
source:      ./app
destination: ./dist

# Social und RSS
twitter_username: kogakure
github_username:  kogakure
subscribe_rss:    "/feed.xml"
feedburner_url:   "http://feeds.feedburner.com/"

# Veröffentlichungs-Einstellungen
future:      true
show_drafts: true
encoding:    "utf-8"
limit_posts: 0

# Server-Konfiguration
date_format: "%d.%m.%Y"
port:        8888
timezone:    local
markdown:    kramdown
lsi:         true

# Kramdown-Konfiguration
kramdown:
  auto_ids:                  true
  auto_id_prefix:            ""
  auto_id_stripping:         true
  transliterated_header_ids: true
  footnote_nr:               1
  entitiy_output:            as_char
  toc_levels:                1..6
  input:                     GFM # GitHub Flavored Markdown
  smart_quotes:              sbquo,lsquo,bdquo,ldquo, # ‚‘ „“
  # smart_quotes:              apos,apos,quot,quot # '' ""

# Dateien ausschließen, Grunt kümmert sich um Assets
exclude: [
  "vendor", "Gemfile", "Gemfile.lock", "README.markdown", "fonts",
  "**.png", "**.jpg", "**.jpeg", "**.gif", "**.webp", "**.svg", "**.ico"
]

# Sitemap.xml Generator
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/htaccess"
    - "/htpasswd"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Lunr Suche
lunr_search:
  excludes:
    - rss.xml
    - sitemap.xml
    - /datenschutz/
    - /faq/
    - /impressum/
    - /index.html
  min_length: 3
  stopwords: "stopwords.txt"

# Jekyll Assets (Development)
assets:
  dirname:        ../.tmp/assets
  baseurl:        /assets/
  js_compressor:  uglifier
  css_compressor: sass
  cachebust:      none
  cache:          false
  debug:          true
  sources:
    - ../.tmp/assets
    - _assets/stylesheets
    - _assets/javascripts
    - _assets/images
    - _assets/javascripts/libs
    - _bower_components
