# ==================== #
# Jekyll-Einstellungen #
# ==================== #
# P R O D U C T I O N  #
# ==================== #

# URLs und Pfade
url:         "http://stefanimhoff.de"
server_path: /home/kogakure/webapps/stefanimhoff

# Veröffentlichungs-Einstellungen
future:      false
show_drafts: false
limit_posts: 0
