# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://localhost:4000  # Development URL
# url: http://stefanimhoff.de # Live URL
title: Stefan Imhoff
description: Frontend Engineer @ XING, Designer, Martial Artist and hobby philosopher.
keywords: Stefan Imhoff, Hamburg, Frontend, Engineer
author: Stefan Imhoff
subscribe_rss: /atom.xml

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root: /
permalink: /blog/:title/ # /notebook/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/kategorien
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb
