baseurl         = "http://localhost:9999/"
title           = "Stefan Imhoff"
languageCode    = "en"
metaDataFormat  = "yaml"
paginate        = 0
buildDrafts     = false
buildFuture     = true
disableKinds    = ["404"]
enableRobotsTXT = true
watch           = true

archetypedir  = "app/archetypes"
contentdir    = "app/content"
dataDir       = "app/data"
layoutdir     = "app/layouts"
publishdir    = "build/development"
staticdir     = "app/static"
themesdir     = "app/themes"

[blackfriday]
  smartypants     = false
  plainIDAnchors  = true
  hrefTargetBlank = true
  extensions      = [""]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[permalinks]
  articles = "/:slug/"

[taxonomies]
  category = "categories"
  series   = "series"

[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 10
[[menu.main]]
  name   = "Articles"
  url    = "/articles/"
  weight = 20
[[menu.main]]
  name   = "Categories"
  url    = "/categories/"
  weight = 30

[[menu.misc]]
  name   = "Haiku"
  url    = "/haiku/"
  weight = 0
[[menu.misc]]
  name   = "Styleguide"
  url    = "/styleguide/"
  weight = 10
[[menu.misc]]
  name   = "Impressum"
  url    = "/impressum/"
  weight = 20

[params]
  criticalcss    = false

  [params.attribution]
  name     = "「大宮盆栽×タムロン」大宮盆栽美術館で盆栽撮影にチャレンジ！ブロガーイベント"
  url      = "https://www.flickr.com/photos/norio-nakayama/9156103138"
  author   = "Norio NAKAYAMA"
  cc       = true
  language = "ja"
