---
# ----------- #
#   Website   #
# ----------- #

theme:
  name: kogakure
  stylesheets_dir: assets/stylesheets
  javascripts_dir: source/javascripts

url: http://stefanimhoff.de
title: Stefan Imhoff
author: "Stefan Imhoff"
description: "Frontend Engineer @ XING, Designer, Martial Artist and hobby philosopher."
keywords: "Stefan Imhoff, Hamburg, Frontend, Engineer"
twitter: "@kogakure"
googleplus: "104687479698350625994"
geo_latitude: "53.596835"
geo_longitude: "10.102015"

date_format: "%d.%m.%Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: "/atom.xml"
subscribe_email:
category_feeds: false
# RSS feeds can list your email address if you like
email:

titlecase: false                    # Converts page and post titles to titlecase

excerpt_link: "Weiterlesen &arr;"   # "Continue reading" link text at the bottom of excerpted articles
excerpt_in_feed: false              # Truncate excerpted articles in the atom feed
permalink_label: "Permalink"
permalink_label_feed: "★ Permalink"
linklog_marker: "→"
linklog_marker_position: after
linklog_marker_position_feed: after
standard_post_marker:

# Disable all comments by default.  If you're using Disqus, or a custom comment system, add
# "use_comments: true" to your site.yml.
use_comments: false
